ombrellificio/config/routes.rb
Rails.application.routes.draw do
  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to
  # Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the
  # :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being
  # the default of "spree".
  mount Spree::Core::Engine, at: '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  # Add your extension routes here
  post '/price_flag' => 'price#calcola_bandiera'
  post '/price_beachflag' => 'price#calcola_beachflag'
  post '/price_fialri' => 'price#calcola_filari'

  resources :uploads

  # pagine statiche
  get '/home' => 'static#home'
  get '/contacts' => 'static#contatti'
  get '/fidelity' => 'static#fedelta'
  get '/privacy' => 'static#privacy'
  get '/tec' => 'static#tec'

  get '/admin/orders/:id/uploads' => 'admin/orders#approva_files'

  post '/line_item/:id/approvazione' => 'admin/line_items#approvazione'
  get '/line_item/:id/storico' => 'admin/line_items#storico'

  get '/account' => 'users#profilo_utente'
  get '/account/user' => 'users#profilo_utente'
  get '/account/addresses' => 'users#profilo_indirizzi'
  get '/account/orders' => 'users#profilo_ordini'
  # get '/account/orders/:id' => 'orders#show'
  # get '/account/password/edit' => 'users#modifica_password'
  # get '/account/email/edit' => 'users#modifica_email'
  # get '/account/corporate_data/edit' => 'users#modifica_dati_azienda'
  # post 'user/modifica_password' => 'users#modifica_password_save'
  # post 'user/modifica_email' => 'users#modifica_email_save'
  # post 'user/modifica_dati_azienda' => 'users#modifica_dati_azienda_save'

end

ombrellificio/app/views/spree/admin/orders/_body_storico.html.erb
<% if @item.storico_files.nil? %>
  <%= "Nessun evento" %>
<% else %>
  <% @item.storico_files_decoded.each do |evento| %>
    <h3><%= evento[:azione] %></h3>
    <p><%= evento[:timestamp] %></p></br>
    <p><%= evento[:info] %></p>
  <% end %>
<% end %>

ombrellificio/app/views/spree/admin/orders/approva_files.html.erb
<%= render 'order_actions', order: @order, events: @order_events %>

<%= render 'spree/admin/shared/order_tabs', current: :approva_files %>

<div data-hook="admin_order_edit_header">
  <%= render 'spree/admin/shared/error_messages', target: @order %>
</div>

<h1>Prodotti Personalizzati che necessitano di un file di stampa</h1>


<table id='line-items' class="table" data-hook="order_details">
  <col width="15%" valign="middle" halign="center">
  <col width="45%" valign="middle">
  <col width="40%" valign="middle">

  <thead data-hook>
    <tr class="active" data-hook="order_details_line_items_headers">
      <th colspan="2">Prodotto Ordinato</th>
      <th class="price">File caricati</th>
    </tr>
  </thead>

  <tbody data-hook>
    <% @order.line_items.each do |item| %>
    <% if item.product.personalizzabile == 1 %>
        <tr data-hook="order_details_line_item_row">
          <td data-hook="order_item_image">
            <% if item.variant.images.length == 0 %>
              <%= link_to small_image(item.variant.product), item.variant.product %>
            <% else %>
              <%= link_to image_tag(item.variant.images.first.attachment.url(:small)), item.variant.product %>
            <% end %>
          </td>
          <td data-hook="order_item_description">
            <h4><%= item.name %></h4>
            <%= item.more_options %>
          </td>
          <td><div>
            <%= form_tag do %>
              <%= link_to_with_icon 'save', "Approva File", "#", class: 'btn btn-success btn-sm', id: "approva_#{item.id}", no_text: true, title: "Approva File" %>
              <%= link_to_with_icon 'delete', "Disapprova File", "#", class: 'btn btn-danger btn-sm', data: { toggle: "modal", target: "#modal_disapprovazione_#{item.id}" }, title: "Disapprova File", no_text: true %>
              <!-- Modal "motivazione Disapprovazione" -->
              <div class="modal fade" id="modal_disapprovazione_<%= item.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <h4 class="modal-title" id="myModalLabel">Motiva la Disapprovazione File</h4>
                    </div>
                    <div class="modal-body">
                      <textarea id="motivazione_disapprovazione_<%= item.id %>" rows=10 style="width: 100%">il file non è stato approvato
La Invitiamo a consultare la nostra guida sui file da caricare</textarea>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                      <button type="button" class="btn btn-primary" id="disapprova_<%= item.id %>" data-dismiss="modal">Disapprova File</button>
                    </div>
                  </div>
                </div>
              </div>
              <!-- , data: { toggle: "modal", target: "#modal_storico_#{item.id}"} -->
              <%= link_to_with_icon 'arrow-left', "Visualizza Storico", "#", id: "storico_#{item.id}", class: 'btn btn-default btn-sm', title: "Visualizza storico", no_text: true %>
              <!-- Modal "storico files" -->
              <div class="modal fade" id="modal_storico_<%= item.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <h4 class="modal-title" id="myModalLabel">Storico Files</h4>
                    </div>
                    <div class="modal-body" id="body_storico_<%= item.id %>">
                      ...
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
            <%= form_for(Spree::Upload.new, html: {id: "new_upload_#{item.id}", multipart: true, class: "dropzone"}) do |f|  %>
              <%= hidden_field_tag "upload[order_id]", @order.id %>
              <%= hidden_field_tag "upload[line_item_id]", item.id %>
              <div class="fallback">
                <%= f.file_field :image %><br>
                <%= f.submit "Upload" %>
              </div>
            <% end %>
          </div></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<script type="text/javascript">
Dropzone.autoDiscover = false;
  <% @order.line_items.each do |item| %>
    new Dropzone("#new_upload_<%= item.id %>", {

      //url: "/upload_photo", // You can override url of form in here.

      //maxFiles: 10, // da errore e non ti fa togliere il file, da gestire noi
      maxFilesize: 50, // in MB
      maxFiles: 10,
      parallelUploads: 1,

      acceptedFiles:'.jpg, .png, .jpeg',// .pdf, .ai, .eps', // type of files

      // non mettendone una mantiene le proprozioni
      //thumbnailWidth: 120,
      //thumbnailHeight: 120,

      // changed the passed param to one accepted by
      // our rails app
      paramName: "upload[image]",

      addRemoveLinks: true,

      success: function(file, response){
  			// find the remove button link of the uploaded file and give it an id
  			// based of the fileID response from the server
  			$(file.previewTemplate).find('.dz-remove').attr('id', response.fileID);
  			// add the dz-success class (the green tick sign)
  			$(file.previewElement).addClass("dz-success");
  		},
  		//when the remove button is clicked
  		removedfile: function(file){
  			// grap the id of the uploaded file we set earlier
  			var id = $(file.previewTemplate).find('.dz-remove').attr('id');

  			// make a DELETE ajax request to delete the file
  			$.ajax({
  				type: 'DELETE',
  				url: '/uploads/' + id,
  				success: function(data){
  					console.log(data.message);
            // TOLGO ANTEPRIMA
            $(document).find(file.previewElement).remove();
  				}
  			});
      },
      // aggiungo file gia presenti nel server
      init: function () {
        <% item.upload.each do |file| %>
          var mockFile = {name: "<%= file.image_file_name %>", size: <%= file.image_file_size %>, type: '<%= file.image_content_type %>', accepted: true };
          this.options.addedfile.call(this, mockFile);
          this.options.thumbnail.call(this, mockFile, "<%= "/spree/uploads/ord_#{@order.id}/li_#{item.id}/#{file.id}/thumb/#{file.image_file_name}" %>");
          // aggiungo id per rimozione file
          $(mockFile.previewTemplate).find('.dz-remove').attr('id', <%= file.id %>);
          mockFile.previewElement.classList.add('dz-success');
          mockFile.previewElement.classList.add('dz-complete');
        <% end %>
      }
    }); // new dropzone

    //link ad ajax per verifica file
    //$("#approva_<%= item.id %>").click(inviaApprovazioneFile(<%= item.id %>, "approvato", ""));
    //$("#disapprova_<%= item.id %>").click(inviaApprovazioneFile(<%= item.id %>, "disapprovato", $("#motivazione_disapprovazione_<%= item.id %>").val()));
    $("#approva_<%= item.id %>").click(function(){
      $.ajax({
        type: 'POST',
        url: '/line_item/' + <%= item.id %> + '/approvazione',
        data: {line_item_id: <%= item.id %>, approvazione: "approvato", info: ""},
        success: function(data){
          console.log(data.message);
        }
      });
    });
    $("#disapprova_<%= item.id %>").click(function(){
      $.ajax({
        type: 'POST',
        url: '/line_item/' + <%= item.id %> + '/approvazione',
        data: {line_item_id: <%= item.id %>, approvazione: "disapprovato", info: $("#motivazione_disapprovazione_<%= item.id %>").serialize()},
        success: function(data){
          console.log(data.message);
        }
      });
    });
    $("#storico_<%= item.id %>").click(function(){
    $("#body_storico_<%= item.id %>").html("Loading...");
    $("#modal_storico_<%= item.id %>").modal({});
      $.ajax({
        async: true,
        type: 'GET',
        url: '/line_item/' + <%= item.id %> + '/storico',
        success: function(data){
          //console.log(data);
          $("#body_storico_<%= item.id %>").html(data);
        }
      });
    });

  <% end %>
  // verifica files

  inviaApprovazioneFile = function inviaApprovazioneFile(line_item_id, approvazione, info){
    console.log("bla");
    alert("bla "+line_item_id);
    $.ajax({
      type: 'POST',
      url: '/line_item/' + line_item_id + '/approvazione',
      data: {line_item_id: line_item_id, approvazione: approvazione, info: info},
      success: function(data){
        console.log(data.message);
      }
    });
  }
</script>

ombrellificio/app/views/spree/admin/orders/index.html.erb
<!-- # BACKEND elenco ordini con riepilogo -->

<% content_for :page_title do %>
  <%= plural_resource_name(Spree::Order) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_order), new_admin_order_url, class: "btn-success", icon: 'add', id: 'admin_new_order' %>
<% end if can? :create, Spree::Order %>

<% content_for :table_filter do %>
  <div data-hook="admin_orders_index_search">

    <%= search_form_for [:admin, @search] do |f| %>
      <div class="row">
        <div class="date-range-filter col-xs-12 col-md-8">
          <div class="form-group">
            <%= label_tag :q_created_at_gt, Spree.t(:date_range) %>
            <div class="row no-padding-bottom">
              <div class="col-xs-12 col-md-6">
                <div class="input-group">
                  <%= f.text_field :created_at_gt, class: 'datepicker datepicker-from form-control', value: params[:q][:created_at_gt], placeholder: Spree.t(:start) %>
                  <span class="input-group-addon">
                    <i class="icon icon-calendar"></i>
                  </span>
                </div>

              </div>
              <div class="col-xs-12 col-md-6">
                <div class="input-group">
                  <%= f.text_field :created_at_lt, class: 'datepicker datepicker-to form-control', value: params[:q][:created_at_lt], placeholder: Spree.t(:stop) %>
                  <span class="input-group-addon">
                    <i class="icon icon-calendar"></i>
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-xs-12 col-md-4">
          <div class="form-group">
            <%= label_tag :q_number_cont, Spree.t(:order_number, number: '') %>
            <%= f.text_field :number_cont, class: 'form-control js-quick-search-target' %>
          </div>
        </div>

      </div>

      <div class="row">

        <div class="col-xs-12 col-md-4">
          <div class="form-group">
            <%= label_tag :q_state_eq, Spree.t(:status) %>
            <%= f.select :state_eq, Spree::Order.state_machines[:state].states.map {|s| [Spree.t("order_state.#{s.name}"), s.value]}, {include_blank: true}, class: 'select2 js-filterable' %>
          </div>
        </div>

        <div class="col-xs-12 col-md-4">
          <div class="form-group">
            <%= label_tag :q_payment_state_eq, Spree.t(:payment_state) %>
            <%= f.select :payment_state_eq, Spree::Order::PAYMENT_STATES.map {|s| [Spree.t("payment_states.#{s}"), s]}, {include_blank: true}, class: 'select2 js-filterable' %>
          </div>
        </div>

        <div class="col-xs-12 col-md-4">
          <div class="form-group">
            <%= label_tag :q_shipment_state_eq, Spree.t(:shipment_state) %>
            <%= f.select :shipment_state_eq, Spree::Order::SHIPMENT_STATES.map {|s| [Spree.t("shipment_states.#{s}"), s]}, {include_blank: true}, class: 'select2 js-filterable' %>
          </div>
        </div>

      </div>

      <div class="row">

        <div class="col-xs-12 col-md-4">
          <div class="form-group">
            <%= label_tag :q_bill_address_firstname_start, Spree.t(:first_name_begins_with) %>
            <%= f.text_field :bill_address_firstname_start, class: 'form-control' %>
          </div>
        </div>

        <div class="col-xs-12 col-md-4">
          <div class="form-group">
            <%= label_tag :q_bill_address_lastname_start, Spree.t(:last_name_begins_with) %>
            <%= f.text_field :bill_address_lastname_start, class: 'form-control' %>
          </div>
        </div>

        <div class="col-xs-12 col-md-4">
          <div class="form-group">
            <%= label_tag :q_email_cont, Spree.t(:email) %>
            <%= f.text_field :email_cont, class: 'form-control js-filterable' %>
          </div>
        </div>

      </div>

      <div class="row">

        <div class="col-xs-12 col-md-4">
          <div class="form-group">
            <%= label_tag :q_line_items_variant_sku_eq, Spree.t(:sku) %>
            <%= f.text_field :line_items_variant_sku_eq, class: 'form-control' %>
          </div>
        </div>

        <div class="col-xs-12 col-md-4">
          <div class="form-group">
            <%= label_tag :q_promotions_id_in, Spree.t(:promotion) %>
            <%= f.select :promotions_id_in, Spree::Promotion.applied.pluck(:name, :id), {include_blank: true}, class: 'select2' %>
          </div>
        </div>

        <div class="col-xs-12 col-md-4">

          <div class="form-group">

            <div class="checkbox">
              <%= label_tag 'q_completed_at_not_null' do %>
                <%= f.check_box :completed_at_not_null, {checked: @show_only_completed}, '1', '0' %>
                <%= Spree.t(:show_only_complete_orders) %>
              <% end %>
            </div>

            <div class="checkbox">
              <%= label_tag 'q_considered_risky_eq' do %>
                <%= f.check_box :considered_risky_eq, {checked: (params[:q][:considered_risky_eq] == '1')}, '1', '' %>
                <%= Spree.t(:show_only_considered_risky) %>
              <% end %>
            </div>

          </div>

        </div>

      </div>

      <div data-hook="admin_orders_index_search_buttons" class="form-actions">
        <%= button Spree.t(:filter_results), 'search' %>
      </div>

    <% end %>

  </div>

<% end %>

<%= render 'spree/admin/shared/index_table_options', collection: @orders %>

<% if @orders.any? %>
  <table class="table" id="listing_orders" data-hook>
    <thead>
      <tr data-hook="admin_orders_index_headers">
        <% if @show_only_completed %>
          <th><%= sort_link @search, :completed_at,   I18n.t(:completed_at, scope: 'activerecord.attributes.spree/order') %></th>
        <% else %>
          <th><%= sort_link @search, :created_at,     I18n.t(:created_at, scope: 'activerecord.attributes.spree/order') %></th>
        <% end %>
        <th><%= sort_link @search, :number,           I18n.t(:number, scope: 'activerecord.attributes.spree/order') %></th>
        <th><%= sort_link @search, :considered_risky, I18n.t(:considered_risky, scope: 'activerecord.attributes.spree/order') %></th>
        <th><%= sort_link @search, :state,            I18n.t(:state, scope: 'activerecord.attributes.spree/order') %></th>
        <th><%= sort_link @search, :upload_confermati,     "upload state" %></th>
        <th><%= sort_link @search, :payment_state,    I18n.t(:payment_state, scope: 'activerecord.attributes.spree/order') %></th>
         <% if Spree::Order.checkout_step_names.include?(:delivery) %>
          <th><%= sort_link @search, :shipment_state, I18n.t(:shipment_state, scope: 'activerecord.attributes.spree/order') %></th>
         <% end %>
        <th><%= sort_link @search, :email,            I18n.t(:email, scope: 'activerecord.attributes.spree/order') %></th>
        <th><%= sort_link @search, :total,            I18n.t(:total, scope: 'activerecord.attributes.spree/order') %></th>
        <th data-hook="admin_orders_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
    <% @orders.each do |order| %>
      <tr data-hook="admin_orders_index_rows" class="state-<%= order.state.downcase %> <%= cycle('odd', 'even') %>">
        <td>
          <%= order_time(@show_only_completed ? order.completed_at : order.created_at) %>
        </td>
        <td><%= link_to order.number, edit_admin_order_path(order) %></td>
        <td>
          <span class="label label-<%= order.considered_risky ? 'considered_risky' : 'considered_safe' %>">
            <%= order.considered_risky ? Spree.t("risky") : Spree.t("safe") %>
          </span>
        </td>
        <td>
          <span class="label label-<%= order.state.downcase %>"><%= Spree.t("order_state.#{order.state.downcase}") %></span>
          <span class="icon icon-filter filterable js-add-filter" data-ransack-field="q_state_eq" data-ransack-value="<%= order.state %>"></span>
        </td>
        <td>
          <span class="label label-<%= order.stato_files.downcase %>"><%= order.stato_files %></span>
          <span class="icon icon-filter filterable js-add-filter" data-ransack-field="q_upload_confermati_eq" data-ransack-value="<%= order.stato_files %>"></span>
        </td>
        <td>
          <% if order.payment_state %>
            <span class="label label-<%= order.payment_state %>"><%= link_to Spree.t("payment_states.#{order.payment_state}"), admin_order_payments_path(order) %></span>
            <span class="icon icon-filter filterable js-add-filter" data-ransack-field="q_payment_state_eq" data-ransack-value="<%= order.payment_state %>"></span>
          <% end %>
        </td>
        <% if Spree::Order.checkout_step_names.include?(:delivery) %>
          <td>
            <% if order.shipment_state %>
              <span class="label label-<%= order.shipment_state %>"><%= Spree.t("shipment_states.#{order.shipment_state}") %></span>
              <span class="icon icon-filter filterable js-add-filter" data-ransack-field="q_shipment_state_eq" data-ransack-value="<%= order.shipment_state %>"></span>
            <% end %>
          </td>
        <% end %>
        <td>
          <% if order.user %>
            <%= link_to order.email, edit_admin_user_path(order.user) %>
          <% else %>
            <%= mail_to order.email %>
          <% end %>
          <% if order.user || order.email %>
            <span class="icon icon-filter filterable js-add-filter" data-ransack-field="q_email_cont" data-ransack-value="<%= order.email %>"></span>
          <% end %>
        </td>
        <td><%= order.display_total.to_html %></td>
        <td class='actions actions-1' data-hook="admin_orders_index_row_actions">
          <%= link_to_edit_url edit_admin_order_path(order), title: "admin_edit_#{dom_id(order)}", no_text: true if can?(:edit, order) %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Order)) %>,
    <%= link_to(Spree.t(:add_one), new_admin_order_url) if can? :create, Spree::Order %>!
  </div>
<% end %>

<%= render 'spree/admin/shared/index_table_options', collection: @orders, simple: true %>