ombrellificio/config/routes.rb
Rails.application.routes.draw do
  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to
  # Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the
  # :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being
  # the default of "spree".
  mount Spree::Core::Engine, at: '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  # Add your extension routes here
  post '/price_flag' => 'price#calcola_bandiera'
  post '/price_beachflag' => 'price#calcola_beachflag'
  post '/price_fialri' => 'price#calcola_filari'

  resources :uploads

  # pagine statiche
  get '/home' => 'static#home'
  get '/contacts' => 'static#contatti'
  get '/fidelity' => 'static#fedelta'
  get '/privacy' => 'static#privacy'
  get '/tec' => 'static#tec'

  get '/admin/orders/:id/uploads' => 'admin/orders#approva_files'

  post '/line_item/:id/approvazione' => 'admin/line_items#approvazione'
  get '/line_item/:id/storico' => 'admin/line_items#storico'

  get '/account' => 'users#profilo_utente'
  get '/account/user' => 'users#profilo_utente'
  get '/account/addresses' => 'users#profilo_indirizzi'
  get '/account/orders' => 'users#profilo_ordini'
  # get '/account/orders/:id' => 'orders#show'
  # get '/account/password/edit' => 'users#modifica_password'
  # get '/account/email/edit' => 'users#modifica_email'
  # get '/account/corporate_data/edit' => 'users#modifica_dati_azienda'
  # post 'user/modifica_password' => 'users#modifica_password_save'
  # post 'user/modifica_email' => 'users#modifica_email_save'
  # post 'user/modifica_dati_azienda' => 'users#modifica_dati_azienda_save'

end

ombrellificio/app/views/spree/admin/shared/_order_tabs.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:orders), admin_orders_path %> /
  <%= link_to @order.number, spree.edit_admin_order_path(@order) %>
<% end %>

<% content_for :sidebar do %>
  <ul class="nav nav-pills nav-stacked" data-hook="admin_order_tabs">
    <% if ((can? :update, @order) && (@order.shipments.size.zero? || @order.shipments.shipped.size.zero?)) %>
      <li<%== ' class="active"' if current == :cart %> data-hook='admin_order_tabs_cart_details'>
        <%= link_to_with_icon 'edit', Spree.t(:cart), cart_admin_order_url(@order) %>
      </li>
    <% end %>

    <% if can?(:update, @order) && @order.checkout_steps.include?("address") %>
      <li<%== ' class="active"' if current == :customer_details %> data-hook='admin_order_tabs_customer_details'>
        <%= link_to_with_icon 'user', Spree.t(:customer), spree.admin_order_customer_url(@order) %>
      </li>
    <% end %>

    <% if can? :update, @order %>
      <li<%== ' class="active"' if current == :shipments %> data-hook='admin_order_tabs_shipment_details'>
        <%= link_to_with_icon 'road', Spree.t(:shipments), edit_admin_order_url(@order) %>
      </li>
    <% end %>

    <% if can? :index, Spree::Adjustment %>
      <li<%== ' class="active"' if current == :adjustments %> data-hook='admin_order_tabs_adjustments'>
        <%= link_to_with_icon 'wrench', Spree.t(:adjustments), spree.admin_order_adjustments_url(@order) %>
      </li>
    <% end %>

    <% if can?(:index, Spree::Payment) %>
      <li<%== ' class="active"' if current == :payments %> data-hook='admin_order_tabs_payments'>
        <%= link_to_with_icon 'credit-card', Spree.t(:payments), spree.admin_order_payments_url(@order) %>
      </li>
    <% end %>

    <% if can? :index, Spree::ReturnAuthorization %>
      <% if @order.completed? %>
        <li<%== ' class="active"' if current == :return_authorizations %> data-hook='admin_order_tabs_return_authorizations'>
          <%= link_to_with_icon 'transfer', Spree.t(:return_authorizations), spree.admin_order_return_authorizations_url(@order) %>
        </li>
      <% end %>
    <% end %>

    <% if can? :index, Spree::CustomerReturn %>
      <% if @order.completed? %>
        <li<%== ' class="active"' if current == :customer_returns %>>
          <%= link_to_with_icon 'transfer', Spree.t(:customer_returns), spree.admin_order_customer_returns_url(@order) %>
        </li>
      <% end %>
    <% end %>

    <% if can? :update, @order %>
      <li<%== ' class="active"' if current == :state_changes %> data-hook='admin_order_tabs_state_changes'>
        <%= link_to_with_icon 'refresh', Spree::StateChange.human_attribute_name(:state_changes), spree.admin_order_state_changes_url(@order) %>
      </li>
    <% end %>

    <% if can? :index, @order %>
      <li<%== ' class="active"' if current == :approva_files %> data-hook='admin_order_tabs_approva_files'>
        <%= link_to_with_icon 'transfer', 'Controllo File', "/admin/orders/#{@order.number}/uploads" %>
      </li>
    <% end %>
  </ul>
<% end %>